/**
 * Backfill metadata header to existing raw.md files.
 *
 * Reads meta.json (sourceUrl, runAt) + extracts title from raw.md first line,
 * prepends a metadata header to the top of each raw.md.
 *
 * Does NOT re-run VLM — just prepends metadata. Safe (no data change).
 *
 * Usage: bun run src/backfill-metadata.ts
 */

import { listDays, readRawMd, saveRawMd, readMeta, listPhotos } from "./lib/storage.js";

const ACCOUNT_NAME = "INFO LENGGER (Nyawiji Ing Seni)";

async function main() {
  const days = await listDays();
  console.log(`Backfilling metadata to ${days.length} day(s):\n`);

  for (const day of days) {
    const meta = await readMeta(day.date);
    if (!meta) {
      console.warn(`${day.date}: no meta — skipping`);
      continue;
    }
    const rawMd = await readRawMd(day.date);
    if (!rawMd) {
      console.warn(`${day.date}: no raw.md — skipping`);
      continue;
    }

    // Skip if metadata header already present
    if (rawMd.startsWith("; ── Metadata")) {
      console.log(`${day.date}: already has metadata — skipping`);
      continue;
    }

    // Extract title from first non-empty line (e.g. "Info Lengger Selasa, 22 September 2026")
    const firstLine = rawMd.split("\n").find((l) => l.trim()) || "";
    const photos = await listPhotos(day.date);

    const header = [
      `; ── Metadata (auto-generated by pipeline) ──`,
      `; Title: ${firstLine}`,
      `; Sumber URL: ${meta.sourceUrl || "(none)"}`,
      `; Author: ${ACCOUNT_NAME}`,
      `; Tanggal capture: ${meta.runAt}`,
      `; Foto: ${photos.join(", ")}`,
      `; ────────────────────────────────────────────`,
      ``,
    ].join("\n");

    await saveRawMd(day.date, header + rawMd);
    console.log(`${day.date}: ✓ metadata prepended (${header.length} chars)`);
  }
  console.log("\nDone.");
}

main().catch((err) => {
  console.error("FATAL:", err);
  process.exit(1);
});
