import type { GeoWilayahEntry } from './types'

/**
 * GPS Coordinates for Wonosobo desa — generated by geocode-wilayah.ts
 * Source: OpenStreetMap Nominatim
 * Generated: 2026-05-28
 * Total: 11 desa (out of ~265 total)
 * Progressive: will be filled incrementally from Nominatim + manual input
 * To add more: bun run src/lib/data/wilayah/_scripts/geocode-wilayah.ts --level desa --tier 1 --output
 */

export const GEO_DESA_WONOSOBO: Record<string, GeoWilayahEntry> = {
  // Kec. 33.07.01 (Wadaslintang)
  '33.07.01.1007': { kodeKemendagri: '33.07.01.1007', koordinat: { lat: -7.5505, lng: 109.8089, source: 'nominatim', accuracy: 'desa' }, namaWilayah: 'Wadaslintang' },
  '33.07.01.2010': { kodeKemendagri: '33.07.01.2010', koordinat: { lat: -7.5422, lng: 109.7617, source: 'nominatim', accuracy: 'desa' }, namaWilayah: 'Lancar' },
  '33.07.01.2011': { kodeKemendagri: '33.07.01.2011', koordinat: { lat: -7.5242, lng: 109.7808, source: 'nominatim', accuracy: 'desa' }, namaWilayah: 'Somogede' },
  '33.07.01.2013': { kodeKemendagri: '33.07.01.2013', koordinat: { lat: -7.5392, lng: 109.8258, source: 'nominatim', accuracy: 'desa' }, namaWilayah: 'Tirip' },
  '33.07.01.2016': { kodeKemendagri: '33.07.01.2016', koordinat: { lat: -7.516, lng: 109.8218, source: 'nominatim', accuracy: 'desa' }, namaWilayah: 'Ngalian' },
  // Kec. 33.07.02 (Kepil)
  '33.07.02.2005': { kodeKemendagri: '33.07.02.2005', koordinat: { lat: -7.5624, lng: 110.0083, source: 'nominatim', accuracy: 'desa' }, namaWilayah: 'Burat' },
  '33.07.02.2006': { kodeKemendagri: '33.07.02.2006', koordinat: { lat: -7.5439, lng: 110.0163, source: 'nominatim', accuracy: 'desa' }, namaWilayah: 'Bener' },
  '33.07.02.1008': { kodeKemendagri: '33.07.02.1008', koordinat: { lat: -7.5178, lng: 110.0032, source: 'nominatim', accuracy: 'desa' }, namaWilayah: 'Kepil' },
  '33.07.02.2010': { kodeKemendagri: '33.07.02.2010', koordinat: { lat: -7.5036, lng: 110.0126, source: 'nominatim', accuracy: 'desa' }, namaWilayah: 'Kapulogo' },
  '33.07.02.2011': { kodeKemendagri: '33.07.02.2011', koordinat: { lat: -7.5012, lng: 110.0274, source: 'nominatim', accuracy: 'desa' }, namaWilayah: 'Kagungan' },
  // Kec. 33.07.03 (Sapuran)
  '33.07.03.2002': { kodeKemendagri: '33.07.03.2002', koordinat: { lat: -7.4694, lng: 109.9508, source: 'nominatim', accuracy: 'desa' }, namaWilayah: 'Karangsari' },
}
