import type { GeoWilayahEntry } from './types'

/**
 * GPS Coordinates for kabupaten — generated by geocode-wilayah.ts
 * Generated: 2026-05-28
 */

export const GEO_KABUPATEN: Record<string, GeoWilayahEntry> = {
  '33.07': { kodeKemendagri: '33.07', koordinat: { lat: -7.3997999, lng: 109.9209645, source: 'nominatim', accuracy: 'kabupaten' }, namaWilayah: 'Wonosobo', alamatLengkap: 'Wonosobo, Jawa Tengah, Jawa, Indonesia' },
  '33.04': { kodeKemendagri: '33.04', koordinat: { lat: -7.3558733, lng: 109.6600728, source: 'nominatim', accuracy: 'kabupaten' }, namaWilayah: 'Banjarnegara', alamatLengkap: 'Banjarnegara, Jawa Tengah, Jawa, Indonesia' },
  '33.08': { kodeKemendagri: '33.08', koordinat: { lat: -7.5136144, lng: 110.2145133, source: 'nominatim', accuracy: 'kabupaten' }, namaWilayah: 'Magelang', alamatLengkap: 'Magelang, Jawa Tengah, Jawa, Indonesia' },
  '33.23': { kodeKemendagri: '33.23', koordinat: { lat: -7.2397576, lng: 110.1216648, source: 'nominatim', accuracy: 'kabupaten' }, namaWilayah: 'Temanggung', alamatLengkap: 'Temanggung, Jawa Tengah, Jawa, Indonesia' },
  '33.25': { kodeKemendagri: '33.25', koordinat: { lat: -6.91069, lng: 109.71914, source: 'nominatim', accuracy: 'kabupaten' }, namaWilayah: 'Batang', alamatLengkap: 'UDD PMI Kabupaten Batang, Jalan Dokter Sutomo, Commercials, Kauman, Batang, Jawa Tengah, Jawa, 51216, Indonesia' },
  '33.24': { kodeKemendagri: '33.24', koordinat: { lat: -7.0190965, lng: 110.1374757, source: 'nominatim', accuracy: 'kabupaten' }, namaWilayah: 'Kendal', alamatLengkap: 'Kendal, Jawa Tengah, Jawa, Indonesia' },
  '33.02': { kodeKemendagri: '33.02', koordinat: { lat: -7.4550716, lng: 109.1167465, source: 'nominatim', accuracy: 'kabupaten' }, namaWilayah: 'Banyumas', alamatLengkap: 'Banyumas, Jawa Tengah, Jawa, Indonesia' },
  '33.03': { kodeKemendagri: '33.03', koordinat: { lat: -7.32733, lng: 109.3998987, source: 'nominatim', accuracy: 'kabupaten' }, namaWilayah: 'Purbalingga', alamatLengkap: 'Purbalingga, Jawa Tengah, Jawa, Indonesia' },
  '33.01': { kodeKemendagri: '33.01', koordinat: { lat: -7.461671, lng: 108.8046146, source: 'nominatim', accuracy: 'kabupaten' }, namaWilayah: 'Cilacap', alamatLengkap: 'Cilacap, Jawa Tengah, Jawa, Indonesia' },
  '33.05': { kodeKemendagri: '33.05', koordinat: { lat: -7.6439744, lng: 109.6077921, source: 'nominatim', accuracy: 'kabupaten' }, namaWilayah: 'Kebumen', alamatLengkap: 'Kebumen, Jawa Tengah, Jawa, Indonesia' },
  '33.06': { kodeKemendagri: '33.06', koordinat: { lat: -7.7073021, lng: 109.9665117, source: 'nominatim', accuracy: 'kabupaten' }, namaWilayah: 'Purworejo', alamatLengkap: 'Purworejo, Jawa Tengah, Jawa, Indonesia' },
  '33.09': { kodeKemendagri: '33.09', koordinat: { lat: -7.3872118, lng: 110.7038691, source: 'nominatim', accuracy: 'kabupaten' }, namaWilayah: 'Boyolali', alamatLengkap: 'Boyolali, Jawa Tengah, Jawa, Indonesia' },
  '33.22': { kodeKemendagri: '33.22', koordinat: { lat: -7.2876561, lng: 110.4019427, source: 'nominatim', accuracy: 'kabupaten' }, namaWilayah: 'Semarang', alamatLengkap: 'Kabupaten Semarang, Jawa Tengah, Jawa, Indonesia' },
  '33.26': { kodeKemendagri: '33.26', koordinat: { lat: -7.0418471, lng: 109.6198875, source: 'nominatim', accuracy: 'kabupaten' }, namaWilayah: 'Pekalongan', alamatLengkap: 'Pekalongan, Jawa Tengah, Jawa, Indonesia' },
  '33.27': { kodeKemendagri: '33.27', koordinat: { lat: -7.0110802, lng: 109.3914037, source: 'nominatim', accuracy: 'kabupaten' }, namaWilayah: 'Pemalang', alamatLengkap: 'Pemalang, Jawa Tengah, Jawa, Indonesia' },
  '33.20': { kodeKemendagri: '33.20', koordinat: { lat: -6.5994983, lng: 110.7832207, source: 'nominatim', accuracy: 'kabupaten' }, namaWilayah: 'Jepara', alamatLengkap: 'Jepara, Jawa Tengah, Jawa, Indonesia' },
  '33.19': { kodeKemendagri: '33.19', koordinat: { lat: -6.7978494, lng: 110.8679109, source: 'nominatim', accuracy: 'kabupaten' }, namaWilayah: 'Kudus', alamatLengkap: 'Kudus, Jawa Tengah, Jawa, Indonesia' },
  '33.21': { kodeKemendagri: '33.21', koordinat: { lat: -6.9230952, lng: 110.6276667, source: 'nominatim', accuracy: 'kabupaten' }, namaWilayah: 'Demak', alamatLengkap: 'Demak, Jawa Tengah, Jawa, Indonesia' },
  '33.12': { kodeKemendagri: '33.12', koordinat: { lat: -7.9620507, lng: 110.9575733, source: 'nominatim', accuracy: 'kabupaten' }, namaWilayah: 'Wonogiri', alamatLengkap: 'Wonogiri, Jawa Tengah, Jawa, Indonesia' },
  '33.15': { kodeKemendagri: '33.15', koordinat: { lat: -7.0964605, lng: 110.8948834, source: 'nominatim', accuracy: 'kabupaten' }, namaWilayah: 'Grobogan', alamatLengkap: 'Grobogan, Jawa Tengah, Jawa, Indonesia' },
  '33.13': { kodeKemendagri: '33.13', koordinat: { lat: -7.6196965, lng: 111.0698003, source: 'nominatim', accuracy: 'kabupaten' }, namaWilayah: 'Karanganyar', alamatLengkap: 'Karanganyar, Jawa Tengah, Jawa, Indonesia' },
}
